import React, { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useQuery } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Plus, Minus, Save, Trash2, ShieldCheck, RefreshCw, AlertTriangle, CheckCircle2 } from 'lucide-react';
import ProductVisual from '@/components/products/ProductVisual';
import { createProductSnapshot, productDocuments } from '@/lib/productDocuments';
import { productQualityIssues, productQualityStatus, selectedProductQualityInput } from '@/lib/productQuality';

const categoryLabels = { solpanel: 'Solpanel', batteri: 'Batteri', vaxelriktare: 'Växelriktare', optimerare: 'Optimerare', kabel: 'Kabel', montagesystem: 'Montagesystem', ovrigt: 'Övrigt' };
const categoryOrder = ['solpanel', 'vaxelriktare', 'batteri', 'optimerare', 'montagesystem', 'kabel', 'ovrigt'];

function productSnapshotFromSelection(item = {}) {
  return item.product_snapshot || item.snapshot || item.productSnapshot || null;
}

function normalizeSelectedProducts(items) {
  return Array.isArray(items) ? items.map(item => {
    const snapshot = productSnapshotFromSelection(item);
    return {
      product_id: item.product_id || snapshot?.product_id || snapshot?.id,
      product_name: item.product_name || snapshot?.name || '',
      quantity: Number(item.quantity) || 1,
      unit_price: Number(item.unit_price) || Number(snapshot?.price) || 0,
      product_snapshot: snapshot || null,
      documents_snapshot: Array.isArray(item.documents_snapshot) ? item.documents_snapshot : (Array.isArray(snapshot?.documents_snapshot) ? snapshot.documents_snapshot : []),
      technical_snapshot: item.technical_snapshot || snapshot?.technical_data_snapshot || null,
      snapshot_created_at: item.snapshot_created_at || snapshot?.snapshot_created_at || '',
      auto_generated: Boolean(item.auto_generated || snapshot?.auto_generated),
      auto_source: item.auto_source || snapshot?.auto_source || '',
    };
  }).filter(item => item.product_id) : [];
}

function buildSelectedProduct(product, old = {}) {
  const snapshot = createProductSnapshot(product);
  return {
    product_id: product.id,
    product_name: product.name,
    quantity: Number(old.quantity) || 1,
    unit_price: Number(old.unit_price) || Number(product.price) || 0,
    product_snapshot: snapshot,
    documents_snapshot: snapshot?.documents_snapshot || productDocuments(product),
    technical_snapshot: snapshot?.technical_data_snapshot || null,
    snapshot_created_at: snapshot?.snapshot_created_at || new Date().toISOString(),
  };
}

function findCurrentProduct(products, productId) {
  return products.find(product => String(product.id) === String(productId)) || null;
}

function qualityBadge(status, autoGenerated = false) {
  if (autoGenerated) return <Badge className="bg-blue-100 text-blue-700 border-blue-200 text-xs">Auto</Badge>;
  return status.complete ? (
    <Badge className="bg-green-100 text-green-700 border-green-200 text-xs"><CheckCircle2 className="mr-1 h-3 w-3" />Komplett</Badge>
  ) : (
    <Badge className="bg-amber-100 text-amber-700 border-amber-200 text-xs"><AlertTriangle className="mr-1 h-3 w-3" />Ofullständig</Badge>
  );
}

function shortIssues(issues = []) {
  if (!issues.length) return '';
  if (issues.length <= 2) return issues.join(' • ');
  return `${issues.slice(0, 2).join(' • ')} • +${issues.length - 2} till`;
}

function autoSourceLabel(source) {
  if (source === 'panels') return 'Auto från Paneler';
  if (source === 'mounting') return 'Auto från Montage';
  return 'Auto';
}

function matchesSearch(product = {}, search = '') {
  if (!search) return true;
  const haystack = [product.name, product.brand, product.model, product.article_number, product.category]
    .filter(Boolean)
    .join(' ')
    .toLowerCase();
  return haystack.includes(search);
}

export default function ProductSelectionTab({ project, onUpdate }) {
  const [selectedProducts, setSelectedProducts] = useState(() => normalizeSelectedProducts(project.selected_products));
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  useEffect(() => {
    setSelectedProducts(normalizeSelectedProducts(project.selected_products));
    setMessage('');
  }, [project?.id, project?.selected_products]);

  const { data: products = [] } = useQuery({
    queryKey: ['products'],
    queryFn: () => base44.entities.Product.list(),
  });

  const addProduct = (product) => {
    const existing = selectedProducts.find(sp => sp.product_id === product.id);
    setMessage('');
    if (existing) {
      setSelectedProducts(prev => prev.map(sp =>
        sp.product_id === product.id && !sp.auto_generated
          ? buildSelectedProduct(product, { ...sp, quantity: sp.quantity + 1 })
          : sp
      ));
    } else {
      setSelectedProducts(prev => [...prev, buildSelectedProduct(product)]);
    }
  };

  const updateQuantity = (productId, delta) => {
    setSelectedProducts(prev => prev.map(sp => {
      if (sp.product_id !== productId || sp.auto_generated) return sp;
      const newQty = sp.quantity + delta;
      return newQty > 0 ? { ...sp, quantity: newQty } : sp;
    }));
  };

  const removeProduct = (productId) => {
    setSelectedProducts(prev => prev.filter(sp => sp.auto_generated || sp.product_id !== productId));
  };

  const refreshOneSnapshot = (productId) => {
    const existing = selectedProducts.find(item => item.product_id === productId);
    const product = findCurrentProduct(products, productId);
    if (!existing || existing.auto_generated) return;
    if (!product) {
      setMessage('Produkten kunde inte uppdateras eftersom den inte hittades i Produktsortimentet.');
      return;
    }
    setSelectedProducts(prev => prev.map(item => item.product_id === productId ? buildSelectedProduct(product, item) : item));
    setMessage(`Snapshot uppdaterad för ${product.name}. Tryck Spara för att spara i projektet.`);
  };

  const refreshAllSnapshots = () => {
    let updated = 0;
    let skipped = 0;
    setSelectedProducts(prev => prev.map(item => {
      if (item.auto_generated) return item;
      const product = findCurrentProduct(products, item.product_id);
      if (!product) {
        skipped += 1;
        return item;
      }
      updated += 1;
      return buildSelectedProduct(product, item);
    }));
    setMessage(`${updated} snapshot(s) uppdaterade. ${skipped ? `${skipped} produkt(er) hittades inte i sortimentet. ` : ''}Tryck Spara för att spara i projektet.`);
  };

  const selectedQualityRows = selectedProducts.map(sp => {
    const sourceProduct = findCurrentProduct(products, sp.product_id);
    if (sp.auto_generated) return { sp, sourceProduct, status: { complete: true }, issues: [] };
    const qualityInput = selectedProductQualityInput(sp, sourceProduct);
    const status = productQualityStatus(qualityInput);
    return { sp, sourceProduct, status, issues: productQualityIssues(qualityInput) };
  });
  const incompleteSelected = selectedQualityRows.filter(row => !row.status.complete && !row.sp.auto_generated);

  const totalCost = selectedProducts.reduce((sum, sp) => sum + (Number(sp.unit_price) || 0) * (Number(sp.quantity) || 0), 0);
  const normalizedSearch = searchTerm.trim().toLowerCase();
  const filteredProducts = products.filter(product => {
    const category = product.category || 'ovrigt';
    const categoryMatch = activeCategory === 'all' || category === activeCategory;
    return categoryMatch && matchesSearch(product, normalizedSearch);
  });
  const groupedProducts = categoryOrder
    .map(category => ({
      category,
      label: categoryLabels[category] || categoryLabels.ovrigt,
      items: filteredProducts.filter(product => (product.category || 'ovrigt') === category),
      total: products.filter(product => (product.category || 'ovrigt') === category).length,
    }))
    .filter(group => group.items.length || activeCategory === group.category);

  const handleSave = async () => {
    setSaving(true);
    await onUpdate({
      selected_products: selectedProducts,
      total_cost: totalCost,
    });
    setSaving(false);
    setMessage('Produktlistan är sparad i projektet. Automatiska rader styrs av Paneler och Montage.');
  };

  return (
    <div className="space-y-4">
      <Card className="border-0 shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between gap-4">
          <div>
            <CardTitle className="text-lg">Valda produkter</CardTitle>
            <p className="mt-1 text-xs text-muted-foreground">Solpaneler från Paneler-fliken och material från Montage-fliken läggs in automatiskt.</p>
          </div>
          <div className="flex flex-wrap justify-end gap-2">
            <Button onClick={refreshAllSnapshots} disabled={!selectedProducts.length || !products.length} variant="outline" className="gap-2" size="sm">
              <RefreshCw className="w-4 h-4" /> Uppdatera alla snapshots
            </Button>
            <Button onClick={handleSave} disabled={saving} className="gap-2" size="sm">
              <Save className="w-4 h-4" /> {saving ? 'Sparar...' : 'Spara'}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {message && <div className="mb-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900">{message}</div>}
          {incompleteSelected.length > 0 && (
            <div className="mb-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
              <AlertTriangle className="mr-2 inline h-4 w-4" />
              {incompleteSelected.length} vald(a) produkt(er) är ofullständiga. Kontrollera produktsortimentet innan projektet används som färdig offert/projektering.
            </div>
          )}
          {selectedProducts.length === 0 ? (
            <p className="text-muted-foreground text-sm text-center py-6">Inga produkter valda. Lägg till produkter från sortimentet nedan.</p>
          ) : (
            <div className="space-y-3">
              {selectedQualityRows.map(({ sp, sourceProduct, status, issues }) => (
                <div key={sp.product_id} className={`flex items-center justify-between gap-3 p-3 rounded-xl border ${status.complete ? 'bg-muted/50 border-transparent' : 'bg-amber-50/60 border-amber-200'}`}>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="font-medium truncate">{sp.product_name}</p>
                      {sp.product_snapshot && !sp.auto_generated && <Badge className="bg-green-100 text-green-700 border-green-200 text-xs"><ShieldCheck className="mr-1 h-3 w-3" />Snapshot</Badge>}
                      {qualityBadge(status, sp.auto_generated)}
                      {sp.auto_generated && <Badge variant="outline" className="text-xs">{autoSourceLabel(sp.auto_source)}</Badge>}
                    </div>
                    <p className="text-sm text-muted-foreground">{sp.unit_price?.toLocaleString('sv-SE')} SEK/st</p>
                    {!status.complete && <p className="mt-1 text-[11px] text-amber-800">{shortIssues(issues)}</p>}
                    {sp.snapshot_created_at && !sp.auto_generated && <p className="text-[11px] text-muted-foreground">Produktdata låst {new Date(sp.snapshot_created_at).toLocaleString('sv-SE')}</p>}
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    <Button size="sm" variant="outline" className="h-8 gap-1 text-xs" onClick={() => refreshOneSnapshot(sp.product_id)} disabled={!sourceProduct || sp.auto_generated}>
                      <RefreshCw className="w-3.5 h-3.5" /> Uppdatera
                    </Button>
                    <div className="flex items-center gap-2">
                      <Button size="icon" variant="outline" className="h-8 w-8" onClick={() => updateQuantity(sp.product_id, -1)} disabled={sp.auto_generated}>
                        <Minus className="w-3 h-3" />
                      </Button>
                      <span className="w-8 text-center font-semibold">{sp.quantity}</span>
                      <Button size="icon" variant="outline" className="h-8 w-8" onClick={() => updateQuantity(sp.product_id, 1)} disabled={sp.auto_generated}>
                        <Plus className="w-3 h-3" />
                      </Button>
                    </div>
                    <span className="font-semibold w-24 text-right">{(sp.unit_price * sp.quantity).toLocaleString('sv-SE')} SEK</span>
                    <Button size="icon" variant="ghost" className="h-8 w-8 text-destructive" onClick={() => removeProduct(sp.product_id)} disabled={sp.auto_generated}>
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              ))}
              <div className="flex justify-between items-center pt-4 border-t">
                <span className="font-semibold text-lg">Totalt</span>
                <span className="font-bold text-2xl text-primary">{totalCost.toLocaleString('sv-SE')} SEK</span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="border-0 shadow-sm">
        <CardHeader>
          <CardTitle className="text-lg">Produktsortiment</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="mb-4 space-y-3">
            <input
              type="search"
              value={searchTerm}
              onChange={event => setSearchTerm(event.target.value)}
              placeholder="Sök produkt, varumärke eller modell..."
              className="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30"
            />
            <div className="flex flex-wrap gap-2">
              <button type="button" onClick={() => setActiveCategory('all')} className={`rounded-full border px-3 py-1.5 text-xs font-medium ${activeCategory === 'all' ? 'bg-primary text-white border-primary' : 'bg-background text-muted-foreground border-border'}`}>
                Alla ({products.length})
              </button>
              {categoryOrder.map(category => {
                const count = products.filter(product => (product.category || 'ovrigt') === category).length;
                return (
                  <button key={category} type="button" onClick={() => setActiveCategory(category)} className={`rounded-full border px-3 py-1.5 text-xs font-medium ${activeCategory === category ? 'bg-primary text-white border-primary' : 'bg-background text-muted-foreground border-border'}`}>
                    {categoryLabels[category] || categoryLabels.ovrigt} ({count})
                  </button>
                );
              })}
            </div>
            <p className="text-xs text-muted-foreground">Visar {filteredProducts.length} av {products.length} produkter</p>
          </div>
          <div className="space-y-6">
            {filteredProducts.length === 0 ? (
              <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Inga produkter matchar sökningen.</p>
            ) : groupedProducts.map(group => (
              <section key={group.category} className="space-y-3">
                <div className="flex items-center justify-between border-b pb-2">
                  <h3 className="text-sm font-semibold text-foreground">{group.label}</h3>
                  <span className="text-xs font-medium text-muted-foreground">{group.items.length} produkter</span>
                </div>
                <div className="grid grid-cols-1 gap-3 xl:grid-cols-2">
                  {group.items.map(product => {
                    const inProject = selectedProducts.find(sp => sp.product_id === product.id);
                    const status = productQualityStatus(product);
                    const issues = productQualityIssues(product);
                    return (
                      <div key={product.id} className={`grid grid-cols-[88px_1fr_auto] items-center gap-3 rounded-xl border p-3 transition-colors hover:bg-muted/30 ${status.complete ? '' : 'border-amber-200 bg-amber-50/40'}`}>
                        <ProductVisual product={product} className="h-20 w-24" />
                        <div className="min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <p className="truncate font-medium">{product.name}</p>
                            {inProject && <Badge variant="secondary" className="shrink-0 text-xs">{inProject.quantity}st</Badge>}
                            {qualityBadge(status)}
                          </div>
                          <p className="mt-1 text-sm text-muted-foreground">{product.brand} {product.model}</p>
                          <p className="mt-1 text-sm font-semibold">{product.price?.toLocaleString('sv-SE')} SEK</p>
                          {!status.complete && <p className="mt-1 text-[11px] text-amber-800">{shortIssues(issues)}</p>}
                        </div>
                        <Button size="sm" variant="outline" className="shrink-0 gap-1" onClick={() => addProduct(product)} disabled={inProject?.auto_generated}>
                          <Plus className="h-3.5 w-3.5" /> Lägg till
                        </Button>
                      </div>
                    );
                  })}
                </div>
              </section>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
